name: digital_receipt
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_slidable:
  http:
  sqflite:
  path_provider:
  path:
  dio:
  fluttertoast:
  device_info:
  flutter_email_sender:
  firebase_core:
  firebase_auth:
  firebase_messaging:
  flutter_device_type:
  shared_preferences:
  overlay_support:
  cupertino_icons:
  share:
  carousel_pro:
  carousel_slider:
  font_awesome_flutter:
  flutter_mailer:
  flutter_svg:
  image_picker:
  permission_handler:
  wc_form_validators:
  keyboard_actions:
  pin_code_text_field:
  pin_code_fields:
  flare_flutter:
  url_launcher:
  random_color:
  device_preview:
  number_display:
  data_connection_checker: 

  hive:
  hive_flutter:
  google_sign_in:








# TO Generate PDF file
  pdf:
  flutter_full_pdf_viewer:
  esys_flutter_share:

  provider:
  connectivity:
  intl:




dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: any
  build_runner: any
  quiver: any
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/paid-stamp.png
    - assets/images/signature.png
    - assets/icons/
    - assets/logos/
    - assets/BACKGROUND.jpg
    - assets/gmail.png
    - assets/images/
    - assets/images/paid-stamp.png
    - assets/images/signature.png

     # For receipt generation
    - assets/fonts/Montserrat/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MuseoModerno
      fonts:
        - asset: assets/fonts/MuseoModerno/static/MuseoModerno-Regular.ttf
          weight: 700
          
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 700

    - family: Southampton
      fonts:
        - asset: assets/fonts/Southampton/Southampton.ttf
          # weight: 700



  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages